### ISSUE TITLE
Can it be published to HaikuDepot somehow, pls?

### ISSUE THREAD

**Issue by Alexey-T** [roired/CudaText-Haiku#1]
@roired

**Comment by roired** [comment]
Good day Alexey,

I presume it can be. I don't know how to do it yet, nor the requirements to do it, but I'll work on it as soon as the package works fine on Haiku.

I'll keep you posted.

Regards,
RR

**Comment by Begasus** [comment]
@roired forked your repo here, trying to understand how CudaText installation works (for 32bit also) and whats really needed to get the full experience, could you guide me a bit here?
For instance, why are the data and py directories needed in $settingsDir? Do they need to be writable, if not maybe they could go into $dataDir? pinging @Alexey-T also here :)

**Comment by Alexey-T** [comment]
>why are the data and py directories needed in $settingsDir? Do they need to be writable, if not maybe they could go into $dataDir?

yes, Cud needs dirs 'py' and 'data' be copied to settings/ and be writable.
dirs contain preinstalled files + user installed.

**Comment by Begasus** [comment]
Are the files in settings/py and settings/data bound to the architecture?

**Comment by Begasus** [comment]
https://github.com/Alexey-T/CudaText/blob/f9dec7022a259ca190fed08feb127b8d29b26894/app/proc_globdata.pas#L1108

This should be changed to libpython3.7m (libpython3.6 is deprecated at haikuports)

Haven't figured out how, but on 32bit the library is installed in `/boot/system/lib/x86` instead of `/boot/system/lib`, not sure if both can be included?

**Comment by Alexey-T** [comment]
no, they are common, only *pyc (python cache) and binaries (of Cuda) are bound.

**Comment by Alexey-T** [comment]
>should be changed to libpython3.7m

done.

**Comment by Alexey-T** [comment]
Are these paths ok?
```
+    {$ifdef CPU64}
+    exit('/boot/system/develop/lib/libpython3.7m.so');
+    {$else}
+    exit('/boot/system/develop/lib/x86/libpython3.7m.so');
+    {$endif}
```

**Comment by Alexey-T** [comment]
It must be `/boot/system/develop/lib` or `/boot/system/lib` ?

**Comment by Begasus** [comment]
.My bad, indeed /boot/system/develop/lib ;)

**Comment by Begasus** [comment]
> Are these paths ok?

Let me check ...

**Comment by Begasus** [comment]
You are fast with updating the version @Alexey-T ;) started to work on a recipe this morning with version 1.152.0.7, renamed it to 1.152.0.8 and now I see it says 1.152.0.9 :P

**Comment by Begasus** [comment]
Where are the plugins installed? Just did some playing with "Multi Installer" and I saw that they were downloaded, but I can't seem to see where?

**Comment by Begasus** [comment]
Local package seems to be ok, unfortunately the app freezes sometimes and I need to kill it with ProcessControler, after that it won't launch until I reboot :(

**Comment by Alexey-T** [comment]
Plugins are installed to "py" folder - mixed with standard plugins

**Comment by Alexey-T** [comment]
> Local package seems to be ok, unfortunately the app freezes sometimes and I need to kill it with ProcessControler, after that it won't launch until I reboot :(

Also we have a problem with tabs X pressing - so we need the debugger. But we don't have it :(

**Comment by Begasus** [comment]
@roired Pushed some changes to my github account in regards of a recipe, most is based on your work, just used the 32bit version there: https://github.com/Begasus/haikuports/commit/7537b1efa5aa4c7150d3ccc2e735ee41ba37cf5b

**Comment by Begasus** [comment]
> > Local package seems to be ok, unfortunately the app freezes sometimes and I need to kill it with ProcessControler, after that it won't launch until I reboot :(
> 
> Also we have a problem with tabs X pressing - so we need the debugger. But we don't have it :(

Seems to happen only when I scroll the "plugin" menu ...

**Comment by Alexey-T** [comment]
>Seems to happen only when I scroll the "plugin" menu ...

how do you scroll it? I don't undestand. the Plugins top menu item?

**Comment by Begasus** [comment]
> how do you scroll it? I don't undestand. the Plugins top menu item?

Maybe scrolling is the right word, hovering over in the Plugins top menu with the mouse ...

**Comment by Alexey-T** [comment]
so you are hovering over Plugins (or another) main menu items? my codes don't work in this case- this is OS provided menu. top menu bar.

**Comment by Begasus** [comment]
Top menus are fine, it's only when I enter the Plugins "sub-menus" that it freezes (sometimes).

**Comment by Begasus** [comment]
Don't know what changes you made, but just build it again and no freezes any more :+1:

**Comment by Alexey-T** [comment]
I didn't change a thing. Menu is OS native control which is only filled by me

**Comment by Begasus** [comment]
On a side note, does this mean it's using it's internal debugger?

![Lazarus-debug](https://user-images.githubusercontent.com/16057090/147104004-3947e5f7-710c-4c9c-ada9-9b394d417921.png)

**Comment by Alexey-T** [comment]
It's using gdb executable (by default)...

**Comment by Begasus** [comment]
As mentioned in the forum thread: https://discuss.haiku-os.org/t/lazarus-1-9-trunk-qt4-and-qt5-interface-screenshots/5767/286

We need some newer gdb ;)

**Comment by Alexey-T** [comment]
OK, will wait.

**Comment by Begasus** [comment]
I don't think it's strictly related to CudaText, rather an issue for Lazarus?

**Comment by Alexey-T** [comment]
GDB is needed for me, so I can debug why Cud gives an error on pressing X on ui-tab title.

**Comment by Begasus** [comment]
Can't help there, gdb is way off my limits :(

**Comment by Alexey-T** [comment]
Laz also has new experimental fpDebug debugger (internal for free pascal), maybe try to ask about it on Laz forum

**Comment by Begasus** [comment]
Pokes @roired We've been discussing this already, on the forum and here, CudaText can be ported (hence no debugger maybe), but have been waiting on your work to finish up on things, you had/got a 64bit version, I have/got a 32bit version, would be strange with all the help we got here to not release some Haiku package at one point ...
