### ISSUE TITLE
Double click on file does not open file

### ISSUE THREAD

**Issue by roired** [roired/CudaText-Haiku#3]
When double clicking on a text file and CudaText has been set in Filetype preferences as the preferred application to open text files, CudaText launches, but the file doesn't open.

**Comment by roired** [comment]
Does this have something to do with setting 'mimeset -f CudaText'?

**Comment by Alexey-T** [comment]
I made simple Laz app which shows ParamCount/ParamStr in listbox. what does it show on Haiku?
[tst-commandline.zip](https://github.com/roired/CudaText-Haiku/files/6644586/tst-commandline.zip)

**Comment by Alexey-T** [comment]
@roired

**Comment by Alexey-T** [comment]
@roired to run this test on haiku, you need to open Project Options dialog, go to 'additions and overrides' and set Qt5 for project

this is CudaText props:

![Screenshot from 2021-06-14 18-57-59](https://user-images.githubusercontent.com/4154978/121922293-7e928800-cd42-11eb-8fd6-248e8146d563.png)

**Comment by roired** [comment]
@Alexey-T , I expect next week will have time to check this out. I'll let you know the results.
Regards,
RR

**Comment by roired** [comment]
Fixed in 1.133.7-1 Haiku. Double clicking on a Text file opens CudaText and loads said file. Prior to that, need to set CudaText as the preferred editor for text files.
