### ISSUE TITLE
default font name in Haiku?

### ISSUE THREAD

**Issue by Alexey-T** [roired/CudaText-Haiku#4]
I can properly init the haiku's default monospaced font name.
what is the font name?
monospaced font! the issue #2 shows screen with non-monospaced one.

**Comment by Begasus** [comment]
Afaikt Haiku uses Noto as a default font

**Comment by roired** [comment]
It seems so, though my default is Monoid Nerd. If I do install CudaText on a clean VM, without any added fonts, Noto is the default, so it seems.

**Comment by Begasus** [comment]
If this is a requirement it could be added to the recipe (providing Monoid is available there, didn't check) and an option to set it as default font for CudaText?

**Comment by Alexey-T** [comment]
I hardcoded this font name as default

**Comment by Begasus** [comment]
You should put that as a dependency for CudaText in your recipe/script now @roired

**Comment by roired** [comment]
@Begasus ,You mean, add the Noto font to the .PackageInfo?

**Comment by Begasus** [comment]
@roired yes (as mentioned, I never used .PackageInfo to build a port, so I'm not familiar there on how it works)

**Comment by Alexey-T** [comment]
IMO no need to require any font, app will work even without it
